// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lone/ctx.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Ctx struct {
	Creator       string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Sender        string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	FeePercentage string `protobuf:"bytes,5,opt,name=feePercentage,proto3" json:"feePercentage,omitempty"`
	FeeReceiver   string `protobuf:"bytes,6,opt,name=feeReceiver,proto3" json:"feeReceiver,omitempty"`
	ServiceName   string `protobuf:"bytes,7,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
}

func (m *Ctx) Reset()         { *m = Ctx{} }
func (m *Ctx) String() string { return proto.CompactTextString(m) }
func (*Ctx) ProtoMessage()    {}
func (*Ctx) Descriptor() ([]byte, []int) {
	return fileDescriptor_684c197a7924c8a1, []int{0}
}
func (m *Ctx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Ctx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Ctx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Ctx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ctx.Merge(m, src)
}
func (m *Ctx) XXX_Size() int {
	return m.Size()
}
func (m *Ctx) XXX_DiscardUnknown() {
	xxx_messageInfo_Ctx.DiscardUnknown(m)
}

var xxx_messageInfo_Ctx proto.InternalMessageInfo

func (m *Ctx) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Ctx) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Ctx) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Ctx) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Ctx) GetFeePercentage() string {
	if m != nil {
		return m.FeePercentage
	}
	return ""
}

func (m *Ctx) GetFeeReceiver() string {
	if m != nil {
		return m.FeeReceiver
	}
	return ""
}

func (m *Ctx) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func init() {
	proto.RegisterType((*Ctx)(nil), "darxan.lone.lone.Ctx")
}

func init() { proto.RegisterFile("lone/ctx.proto", fileDescriptor_684c197a7924c8a1) }

var fileDescriptor_684c197a7924c8a1 = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x18, 0x84, 0x63, 0x0a, 0x29, 0x18, 0x81, 0x90, 0x07, 0x64, 0x31, 0x58, 0x15, 0x30, 0x30, 0x25,
	0x03, 0x33, 0x0b, 0xec, 0x08, 0x75, 0x64, 0x73, 0xdd, 0x6b, 0x89, 0x44, 0xec, 0xea, 0x8f, 0x5b,
	0x99, 0xb7, 0xe0, 0xb1, 0x18, 0xbb, 0x20, 0x31, 0xa2, 0xe4, 0x45, 0x50, 0x6c, 0x8a, 0xc2, 0x62,
	0xeb, 0xbe, 0xbb, 0xfb, 0x87, 0xe3, 0xa7, 0xaf, 0xce, 0xa2, 0x34, 0x3e, 0x14, 0x2b, 0x72, 0xde,
	0x89, 0xb3, 0xb9, 0xa6, 0xa0, 0x6d, 0xd1, 0xe3, 0xf8, 0x5c, 0x7e, 0x32, 0x3e, 0x7a, 0xf0, 0x41,
	0x48, 0x3e, 0x36, 0x04, 0xed, 0x1d, 0x49, 0x36, 0x61, 0x37, 0x47, 0xd3, 0x9d, 0x14, 0xe7, 0x3c,
	0x6f, 0x60, 0xe7, 0x20, 0xb9, 0x17, 0x8d, 0x5f, 0x25, 0x2e, 0xf8, 0x21, 0xc1, 0xa0, 0xda, 0x80,
	0xe4, 0x28, 0x3a, 0x7f, 0xba, 0xef, 0xe8, 0xda, 0xad, 0xad, 0x97, 0xfb, 0xa9, 0x93, 0x94, 0xb8,
	0xe6, 0x27, 0x0b, 0xe0, 0x09, 0x64, 0x60, 0xbd, 0x5e, 0x42, 0x1e, 0x44, 0xfb, 0x3f, 0x14, 0x13,
	0x7e, 0xbc, 0x00, 0xa6, 0xbb, 0xe3, 0x79, 0xcc, 0x0c, 0x51, 0x9f, 0x68, 0x40, 0x9b, 0xca, 0xe0,
	0x51, 0xd7, 0x90, 0xe3, 0x94, 0x18, 0xa0, 0xfb, 0xbb, 0x8f, 0x56, 0xb1, 0x6d, 0xab, 0xd8, 0x77,
	0xab, 0xd8, 0x7b, 0xa7, 0xb2, 0x6d, 0xa7, 0xb2, 0xaf, 0x4e, 0x65, 0xcf, 0x57, 0xcb, 0xca, 0xbf,
	0xac, 0x67, 0x85, 0x71, 0x75, 0x99, 0xe6, 0x28, 0xe3, 0x4a, 0x21, 0x7d, 0xfe, 0x6d, 0x85, 0x66,
	0x96, 0xc7, 0xbd, 0x6e, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x20, 0x95, 0x1f, 0x03, 0x41, 0x01,
	0x00, 0x00,
}

func (m *Ctx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ctx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Ctx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ServiceName) > 0 {
		i -= len(m.ServiceName)
		copy(dAtA[i:], m.ServiceName)
		i = encodeVarintCtx(dAtA, i, uint64(len(m.ServiceName)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.FeeReceiver) > 0 {
		i -= len(m.FeeReceiver)
		copy(dAtA[i:], m.FeeReceiver)
		i = encodeVarintCtx(dAtA, i, uint64(len(m.FeeReceiver)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.FeePercentage) > 0 {
		i -= len(m.FeePercentage)
		copy(dAtA[i:], m.FeePercentage)
		i = encodeVarintCtx(dAtA, i, uint64(len(m.FeePercentage)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintCtx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintCtx(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintCtx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCtx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCtx(dAtA []byte, offset int, v uint64) int {
	offset -= sovCtx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Ctx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCtx(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovCtx(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovCtx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovCtx(uint64(l))
	}
	l = len(m.FeePercentage)
	if l > 0 {
		n += 1 + l + sovCtx(uint64(l))
	}
	l = len(m.FeeReceiver)
	if l > 0 {
		n += 1 + l + sovCtx(uint64(l))
	}
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovCtx(uint64(l))
	}
	return n
}

func sovCtx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCtx(x uint64) (n int) {
	return sovCtx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Ctx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCtx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ctx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ctx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeePercentage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeReceiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeReceiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCtx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCtx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCtx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCtx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCtx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCtx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCtx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCtx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCtx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCtx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCtx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCtx = fmt.Errorf("proto: unexpected end of group")
)
