// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lone/customTransaction.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CustomTransaction struct {
	Id            uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Creator       string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Sender        string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	FeePercentage string `protobuf:"bytes,6,opt,name=feePercentage,proto3" json:"feePercentage,omitempty"`
	FeeReceiver   string `protobuf:"bytes,7,opt,name=feeReceiver,proto3" json:"feeReceiver,omitempty"`
	ServiceName   string `protobuf:"bytes,8,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
}

func (m *CustomTransaction) Reset()         { *m = CustomTransaction{} }
func (m *CustomTransaction) String() string { return proto.CompactTextString(m) }
func (*CustomTransaction) ProtoMessage()    {}
func (*CustomTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_e355b9c8dfef7af9, []int{0}
}
func (m *CustomTransaction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CustomTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CustomTransaction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CustomTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomTransaction.Merge(m, src)
}
func (m *CustomTransaction) XXX_Size() int {
	return m.Size()
}
func (m *CustomTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_CustomTransaction proto.InternalMessageInfo

func (m *CustomTransaction) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CustomTransaction) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *CustomTransaction) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *CustomTransaction) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *CustomTransaction) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *CustomTransaction) GetFeePercentage() string {
	if m != nil {
		return m.FeePercentage
	}
	return ""
}

func (m *CustomTransaction) GetFeeReceiver() string {
	if m != nil {
		return m.FeeReceiver
	}
	return ""
}

func (m *CustomTransaction) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func init() {
	proto.RegisterType((*CustomTransaction)(nil), "darxan.lone.lone.CustomTransaction")
}

func init() { proto.RegisterFile("lone/customTransaction.proto", fileDescriptor_e355b9c8dfef7af9) }

var fileDescriptor_e355b9c8dfef7af9 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xe3, 0xfc, 0xfd, 0xd3, 0x62, 0x04, 0x02, 0x0f, 0xc8, 0x42, 0xc8, 0x8a, 0x80, 0xa1,
	0x53, 0x32, 0x30, 0xb3, 0xc0, 0x8e, 0x50, 0xc4, 0xc4, 0xe6, 0x3a, 0xb7, 0xc5, 0x12, 0xb1, 0xab,
	0x6b, 0xa7, 0x2a, 0x6f, 0xc1, 0x63, 0x31, 0x76, 0x64, 0x44, 0xc9, 0x23, 0xf0, 0x02, 0x28, 0x36,
	0x45, 0x85, 0xc5, 0xd6, 0x39, 0xe7, 0x3b, 0x77, 0x38, 0xf4, 0xec, 0xd9, 0x1a, 0x28, 0x55, 0xeb,
	0xbc, 0x6d, 0x1e, 0x50, 0x1a, 0x27, 0x95, 0xd7, 0xd6, 0x14, 0x4b, 0xb4, 0xde, 0xb2, 0xa3, 0x5a,
	0xe2, 0x5a, 0x9a, 0x62, 0x80, 0xc2, 0x73, 0xfe, 0x49, 0xe8, 0xf1, 0xed, 0x5f, 0x9a, 0x1d, 0xd2,
	0x54, 0xd7, 0x9c, 0xe4, 0x64, 0x3a, 0xaa, 0x52, 0x5d, 0x33, 0x4e, 0xc7, 0x0a, 0x41, 0x7a, 0x8b,
	0x3c, 0xcd, 0xc9, 0x74, 0xaf, 0xda, 0x4a, 0x76, 0x42, 0x33, 0x07, 0xa6, 0x06, 0xe4, 0xff, 0x42,
	0xf0, 0xad, 0xd8, 0x29, 0x9d, 0x20, 0x28, 0xd0, 0x2b, 0x40, 0x3e, 0x0a, 0xc9, 0x8f, 0x1e, 0x3a,
	0xb2, 0xb1, 0xad, 0xf1, 0xfc, 0x7f, 0xec, 0x44, 0xc5, 0x2e, 0xe9, 0xc1, 0x1c, 0xe0, 0x1e, 0x50,
	0x81, 0xf1, 0x72, 0x01, 0x3c, 0x0b, 0xf1, 0x6f, 0x93, 0xe5, 0x74, 0x7f, 0x0e, 0x50, 0x6d, 0x8f,
	0x8f, 0x03, 0xb3, 0x6b, 0x0d, 0x84, 0x03, 0x5c, 0x69, 0x05, 0x77, 0xb2, 0x01, 0x3e, 0x89, 0xc4,
	0x8e, 0x75, 0x73, 0xfd, 0xd6, 0x09, 0xb2, 0xe9, 0x04, 0xf9, 0xe8, 0x04, 0x79, 0xed, 0x45, 0xb2,
	0xe9, 0x45, 0xf2, 0xde, 0x8b, 0xe4, 0xf1, 0x62, 0xa1, 0xfd, 0x53, 0x3b, 0x2b, 0x94, 0x6d, 0xca,
	0x38, 0x56, 0x19, 0x16, 0x5d, 0xc7, 0xcf, 0xbf, 0x2c, 0xc1, 0xcd, 0xb2, 0xb0, 0xe6, 0xd5, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xa4, 0x7b, 0x2f, 0x6d, 0x01, 0x00, 0x00,
}

func (m *CustomTransaction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CustomTransaction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CustomTransaction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ServiceName) > 0 {
		i -= len(m.ServiceName)
		copy(dAtA[i:], m.ServiceName)
		i = encodeVarintCustomTransaction(dAtA, i, uint64(len(m.ServiceName)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.FeeReceiver) > 0 {
		i -= len(m.FeeReceiver)
		copy(dAtA[i:], m.FeeReceiver)
		i = encodeVarintCustomTransaction(dAtA, i, uint64(len(m.FeeReceiver)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.FeePercentage) > 0 {
		i -= len(m.FeePercentage)
		copy(dAtA[i:], m.FeePercentage)
		i = encodeVarintCustomTransaction(dAtA, i, uint64(len(m.FeePercentage)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintCustomTransaction(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintCustomTransaction(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintCustomTransaction(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCustomTransaction(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintCustomTransaction(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintCustomTransaction(dAtA []byte, offset int, v uint64) int {
	offset -= sovCustomTransaction(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CustomTransaction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovCustomTransaction(uint64(m.Id))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCustomTransaction(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovCustomTransaction(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovCustomTransaction(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovCustomTransaction(uint64(l))
	}
	l = len(m.FeePercentage)
	if l > 0 {
		n += 1 + l + sovCustomTransaction(uint64(l))
	}
	l = len(m.FeeReceiver)
	if l > 0 {
		n += 1 + l + sovCustomTransaction(uint64(l))
	}
	l = len(m.ServiceName)
	if l > 0 {
		n += 1 + l + sovCustomTransaction(uint64(l))
	}
	return n
}

func sovCustomTransaction(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCustomTransaction(x uint64) (n int) {
	return sovCustomTransaction(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CustomTransaction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCustomTransaction
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CustomTransaction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CustomTransaction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeePercentage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeReceiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeReceiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomTransaction
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCustomTransaction(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCustomTransaction
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCustomTransaction(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCustomTransaction
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCustomTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCustomTransaction
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCustomTransaction
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCustomTransaction
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCustomTransaction
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCustomTransaction        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCustomTransaction          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCustomTransaction = fmt.Errorf("proto: unexpected end of group")
)
