// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: lone/customtx.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Customtx struct {
	Index         string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Creator       string `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	Sender        string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver      string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount        string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	FeePercentage string `protobuf:"bytes,6,opt,name=feePercentage,proto3" json:"feePercentage,omitempty"`
	FeeReceiver   string `protobuf:"bytes,7,opt,name=feeReceiver,proto3" json:"feeReceiver,omitempty"`
	ServieName    string `protobuf:"bytes,8,opt,name=servieName,proto3" json:"servieName,omitempty"`
}

func (m *Customtx) Reset()         { *m = Customtx{} }
func (m *Customtx) String() string { return proto.CompactTextString(m) }
func (*Customtx) ProtoMessage()    {}
func (*Customtx) Descriptor() ([]byte, []int) {
	return fileDescriptor_12f25e01edc2214e, []int{0}
}
func (m *Customtx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Customtx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Customtx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Customtx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customtx.Merge(m, src)
}
func (m *Customtx) XXX_Size() int {
	return m.Size()
}
func (m *Customtx) XXX_DiscardUnknown() {
	xxx_messageInfo_Customtx.DiscardUnknown(m)
}

var xxx_messageInfo_Customtx proto.InternalMessageInfo

func (m *Customtx) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *Customtx) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *Customtx) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Customtx) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *Customtx) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Customtx) GetFeePercentage() string {
	if m != nil {
		return m.FeePercentage
	}
	return ""
}

func (m *Customtx) GetFeeReceiver() string {
	if m != nil {
		return m.FeeReceiver
	}
	return ""
}

func (m *Customtx) GetServieName() string {
	if m != nil {
		return m.ServieName
	}
	return ""
}

func init() {
	proto.RegisterType((*Customtx)(nil), "darxan.lone.lone.Customtx")
}

func init() { proto.RegisterFile("lone/customtx.proto", fileDescriptor_12f25e01edc2214e) }

var fileDescriptor_12f25e01edc2214e = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4e, 0xeb, 0x30,
	0x18, 0xc5, 0xe3, 0x7b, 0x69, 0x1a, 0x3e, 0x84, 0x84, 0x0c, 0x42, 0x16, 0x83, 0x55, 0x01, 0x03,
	0x53, 0x32, 0x30, 0xb3, 0xc0, 0x8e, 0x50, 0x47, 0x36, 0xd7, 0x39, 0x2d, 0x91, 0x88, 0x5d, 0x39,
	0x4e, 0x15, 0xde, 0x82, 0xc7, 0x62, 0xec, 0xc8, 0x88, 0x92, 0x9d, 0x67, 0x40, 0xb5, 0x5b, 0x54,
	0x16, 0x5b, 0xbf, 0xf3, 0xe7, 0x1b, 0x0e, 0x9d, 0xbe, 0x5a, 0x83, 0x42, 0xb7, 0x8d, 0xb7, 0xb5,
	0xef, 0xf2, 0xa5, 0xb3, 0xde, 0xf2, 0x93, 0x52, 0xb9, 0x4e, 0x99, 0x7c, 0xe3, 0x85, 0xe7, 0xf2,
	0x9b, 0x51, 0xf6, 0xb0, 0x0d, 0xf1, 0x33, 0x1a, 0x55, 0xa6, 0x44, 0x27, 0xd8, 0x84, 0xdd, 0x1c,
	0x4e, 0x23, 0x70, 0x41, 0x63, 0xed, 0xa0, 0xbc, 0x75, 0xe2, 0x5f, 0xd0, 0x77, 0xc8, 0xcf, 0x29,
	0x6d, 0x60, 0x4a, 0x38, 0xf1, 0x3f, 0x18, 0x5b, 0xe2, 0x17, 0x94, 0x39, 0x68, 0x54, 0x2b, 0x38,
	0x71, 0x10, 0x9c, 0x5f, 0xde, 0x74, 0x54, 0x6d, 0x5b, 0xe3, 0xc5, 0x28, 0x76, 0x22, 0xf1, 0x6b,
	0x3a, 0x9e, 0x03, 0x4f, 0x70, 0x1a, 0xc6, 0xab, 0x05, 0x44, 0x1a, 0xec, 0xbf, 0x22, 0x9f, 0xd0,
	0xd1, 0x1c, 0x98, 0xee, 0x8e, 0x8f, 0x43, 0x66, 0x5f, 0xe2, 0x92, 0xa8, 0x81, 0x5b, 0x55, 0x78,
	0x54, 0x35, 0x44, 0x16, 0x02, 0x7b, 0xca, 0xfd, 0xdd, 0x47, 0x2f, 0xd9, 0xba, 0x97, 0xec, 0xab,
	0x97, 0xec, 0x7d, 0x90, 0xc9, 0x7a, 0x90, 0xc9, 0xe7, 0x20, 0x93, 0xe7, 0xab, 0x45, 0xe5, 0x5f,
	0xda, 0x59, 0xae, 0x6d, 0x5d, 0xc4, 0x9d, 0x8a, 0xb0, 0x61, 0x17, 0x3f, 0xff, 0xb6, 0x44, 0x33,
	0x4b, 0xc3, 0x90, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x59, 0x62, 0xa3, 0x5f, 0x01,
	0x00, 0x00,
}

func (m *Customtx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Customtx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Customtx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ServieName) > 0 {
		i -= len(m.ServieName)
		copy(dAtA[i:], m.ServieName)
		i = encodeVarintCustomtx(dAtA, i, uint64(len(m.ServieName)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.FeeReceiver) > 0 {
		i -= len(m.FeeReceiver)
		copy(dAtA[i:], m.FeeReceiver)
		i = encodeVarintCustomtx(dAtA, i, uint64(len(m.FeeReceiver)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.FeePercentage) > 0 {
		i -= len(m.FeePercentage)
		copy(dAtA[i:], m.FeePercentage)
		i = encodeVarintCustomtx(dAtA, i, uint64(len(m.FeePercentage)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Amount) > 0 {
		i -= len(m.Amount)
		copy(dAtA[i:], m.Amount)
		i = encodeVarintCustomtx(dAtA, i, uint64(len(m.Amount)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintCustomtx(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintCustomtx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintCustomtx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintCustomtx(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCustomtx(dAtA []byte, offset int, v uint64) int {
	offset -= sovCustomtx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Customtx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovCustomtx(uint64(l))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovCustomtx(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovCustomtx(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovCustomtx(uint64(l))
	}
	l = len(m.Amount)
	if l > 0 {
		n += 1 + l + sovCustomtx(uint64(l))
	}
	l = len(m.FeePercentage)
	if l > 0 {
		n += 1 + l + sovCustomtx(uint64(l))
	}
	l = len(m.FeeReceiver)
	if l > 0 {
		n += 1 + l + sovCustomtx(uint64(l))
	}
	l = len(m.ServieName)
	if l > 0 {
		n += 1 + l + sovCustomtx(uint64(l))
	}
	return n
}

func sovCustomtx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCustomtx(x uint64) (n int) {
	return sovCustomtx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Customtx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCustomtx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Customtx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Customtx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePercentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeePercentage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeReceiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeReceiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServieName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCustomtx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCustomtx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCustomtx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServieName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCustomtx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCustomtx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCustomtx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCustomtx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCustomtx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCustomtx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCustomtx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCustomtx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCustomtx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCustomtx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCustomtx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCustomtx = fmt.Errorf("proto: unexpected end of group")
)
